### ISSUE TITLE
navigation bar component

### ISSUE THREAD

**Issue by Wesley-T-Wang** [cse110-fa21-group18/cse110-fa21-group18#7]
mock pages in the figma link 

https://www.figma.com/file/kG7eRwo2Fa4ODhnTBxPTdC/AteTeen?node-id=76%3A970

html basic css, don't worry about final design, we will finalize for all pages when we decide on a bootstrap library and set in place design standards as a team

**Comment by audreyzhao75** [comment]
Finished - as a part of the frontEnd1 branch and injected to every html page
